CREATE TABLE "vestibulon2_program" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "vestibulon2_program_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" varchar(256) NOT NULL,
	"exercise_name" varchar(256) NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"number_of_seconds" integer NOT NULL,
	"number_of_repetions" integer NOT NULL,
	"metronome_bpm" integer NOT NULL,
	"metronome_bpm_temp" integer,
	"position" varchar(256) NOT NULL,
	"background" varchar(256) NOT NULL,
	"recomended_vas" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "vestibulon2_rep" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "vestibulon2_rep_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" varchar(256) NOT NULL,
	"exercise_name" varchar(256) NOT NULL,
	"dizziness" integer,
	"nausea" integer,
	"general_difficulty" integer,
	"rest_time" integer,
	"start_time" timestamp with time zone NOT NULL,
	"end_time" timestamp with time zone,
	"bpm_end_of_rep" integer,
	"flag_interrupted" boolean DEFAULT false,
	"flag_paused" boolean DEFAULT false
);
--> statement-breakpoint
CREATE TABLE "vestibulon2_user_profile" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "vestibulon2_user_profile_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"workos_user_id" varchar(256) NOT NULL,
	"username" varchar(256) NOT NULL,
	"email" varchar(256) NOT NULL,
	"gender" varchar(16),
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	CONSTRAINT "vestibulon2_user_profile_workos_user_id_unique" UNIQUE("workos_user_id"),
	CONSTRAINT "vestibulon2_user_profile_username_unique" UNIQUE("username"),
	CONSTRAINT "vestibulon2_user_profile_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE INDEX "program_user_exercise_idx" ON "vestibulon2_program" USING btree ("user_id","exercise_name");--> statement-breakpoint
CREATE INDEX "rep_user_exercise_idx" ON "vestibulon2_rep" USING btree ("user_id","exercise_name");--> statement-breakpoint
CREATE INDEX "user_profile_workos_user_idx" ON "vestibulon2_user_profile" USING btree ("workos_user_id");--> statement-breakpoint
CREATE INDEX "user_profile_username_idx" ON "vestibulon2_user_profile" USING btree ("username");--> statement-breakpoint
CREATE INDEX "user_profile_email_idx" ON "vestibulon2_user_profile" USING btree ("email");