CREATE TABLE IF NOT EXISTS "vestibulon2_today_reps" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "vestibulon2_today_reps_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" varchar(256) NOT NULL,
	"practice_time" timestamp with time zone NOT NULL,
	"exercise_name" varchar(256) NOT NULL,
	"rep_id" integer
);
--> statement-breakpoint
DO $$
BEGIN
	IF NOT EXISTS (
		SELECT 1
		FROM pg_constraint
		WHERE conname = 'vestibulon2_today_reps_user_id_vestibulon2_user_profile_workos_user_id_fk'
	) THEN
		ALTER TABLE "vestibulon2_today_reps"
		ADD CONSTRAINT "vestibulon2_today_reps_user_id_vestibulon2_user_profile_workos_user_id_fk"
		FOREIGN KEY ("user_id")
		REFERENCES "public"."vestibulon2_user_profile"("workos_user_id")
		ON DELETE cascade
		ON UPDATE no action;
	END IF;
END
$$;--> statement-breakpoint
DO $$
BEGIN
	IF NOT EXISTS (
		SELECT 1
		FROM pg_constraint
		WHERE conname = 'vestibulon2_today_reps_rep_id_vestibulon2_rep_id_fk'
	) THEN
		ALTER TABLE "vestibulon2_today_reps"
		ADD CONSTRAINT "vestibulon2_today_reps_rep_id_vestibulon2_rep_id_fk"
		FOREIGN KEY ("rep_id")
		REFERENCES "public"."vestibulon2_rep"("id")
		ON DELETE set null
		ON UPDATE no action;
	END IF;
END
$$;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "today_rep_user_practice_idx" ON "vestibulon2_today_reps" USING btree ("user_id","practice_time");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "today_rep_user_exercise_idx" ON "vestibulon2_today_reps" USING btree ("user_id","exercise_name");