DO $$ BEGIN
  IF to_regclass('public.vestibulon2_program_history') IS NULL THEN
    DROP SEQUENCE IF EXISTS vestibulon2_program_history_id_seq;
  END IF;
  IF to_regclass('public.vestibulon2_user_session_history') IS NULL THEN
    DROP SEQUENCE IF EXISTS vestibulon2_user_session_history_id_seq;
  END IF;
END $$;
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "vestibulon2_program_history" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "vestibulon2_program_history_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"program_id" integer NOT NULL,
	"user_id" varchar(256) NOT NULL,
	"exercise_name" varchar(256) NOT NULL,
	"number_of_repetions" integer NOT NULL,
	"active" boolean NOT NULL,
	"effective_from" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "vestibulon2_user_session_history" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "vestibulon2_user_session_history_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" varchar(256) NOT NULL,
	"number_of_sessions" integer NOT NULL,
	"effective_from" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "vestibulon2_program_history" ADD CONSTRAINT "vestibulon2_program_history_program_id_vestibulon2_program_id_fk" FOREIGN KEY ("program_id") REFERENCES "public"."vestibulon2_program"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "vestibulon2_program_history" ADD CONSTRAINT "vestibulon2_program_history_user_id_vestibulon2_user_profile_workos_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."vestibulon2_user_profile"("workos_user_id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "vestibulon2_user_session_history" ADD CONSTRAINT "vestibulon2_user_session_history_user_id_vestibulon2_user_profile_workos_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."vestibulon2_user_profile"("workos_user_id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "program_history_program_effective_idx" ON "vestibulon2_program_history" USING btree ("program_id","effective_from");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "program_history_user_exercise_idx" ON "vestibulon2_program_history" USING btree ("user_id","exercise_name");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "user_session_history_user_effective_idx" ON "vestibulon2_user_session_history" USING btree ("user_id","effective_from");
