DO $$ BEGIN
  IF to_regclass('public.vestibulon2_treatment_plan') IS NULL THEN
    DROP SEQUENCE IF EXISTS vestibulon2_treatment_plan_id_seq;
  END IF;
  IF to_regclass('public.vestibulon2_treatment_plan_exercise') IS NULL THEN
    DROP SEQUENCE IF EXISTS vestibulon2_treatment_plan_exercise_id_seq;
  END IF;
END $$;
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "vestibulon2_treatment_plan" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "vestibulon2_treatment_plan_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" varchar(256) NOT NULL,
	"created_by" varchar(256) NOT NULL,
	"number_of_sessions" integer NOT NULL,
	"effective_from" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "vestibulon2_treatment_plan_exercise" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "vestibulon2_treatment_plan_exercise_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"treatment_plan_id" integer NOT NULL,
	"exercise_name" varchar(256) NOT NULL,
	"number_of_seconds" integer NOT NULL,
	"number_of_repetions" integer NOT NULL,
	"metronome_bpm" integer NOT NULL,
	"position" varchar(256) NOT NULL,
	"background" varchar(256) NOT NULL,
	"recomended_vas" integer NOT NULL
);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "vestibulon2_treatment_plan" ADD CONSTRAINT "vestibulon2_treatment_plan_user_id_vestibulon2_user_profile_workos_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."vestibulon2_user_profile"("workos_user_id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "vestibulon2_treatment_plan" ADD CONSTRAINT "vestibulon2_treatment_plan_created_by_vestibulon2_user_profile_workos_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."vestibulon2_user_profile"("workos_user_id") ON DELETE restrict ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "vestibulon2_treatment_plan_exercise" ADD CONSTRAINT "vestibulon2_treatment_plan_exercise_treatment_plan_id_vestibulon2_treatment_plan_id_fk" FOREIGN KEY ("treatment_plan_id") REFERENCES "public"."vestibulon2_treatment_plan"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "treatment_plan_user_effective_idx" ON "vestibulon2_treatment_plan" USING btree ("user_id","effective_from");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "treatment_plan_user_idx" ON "vestibulon2_treatment_plan" USING btree ("user_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "treatment_plan_exercise_plan_idx" ON "vestibulon2_treatment_plan_exercise" USING btree ("treatment_plan_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "treatment_plan_exercise_name_idx" ON "vestibulon2_treatment_plan_exercise" USING btree ("treatment_plan_id","exercise_name");
